# Generated by Django 5.0.5 on 2024-05-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='cars')),
                ('year', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=65)),
                ('enginetype', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Automatic', max_length=20)),
            ],
        ),
    ]
