# Generated by Django 5.0.5 on 2024-05-09 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='year',
            new_name='model',
        ),
        migrations.AddField(
            model_name='cars',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cars',
            name='fuelConsumption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
