# Generated by Django 5.0.5 on 2024-05-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_booking_pickup_date_alter_booking_return_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='additional_information',
        ),
    ]
