# Generated by Django 5.0.5 on 2024-05-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='slides',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
